//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BankPayment
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter bank name.")]
        [StringLength(255, ErrorMessage = "Bank name up to 255 characters.")]
        public string Bank { get; set; }
        [Required(ErrorMessage = "Please enter account number .")]
        public string AccountNumber { get; set; }
        [Required(ErrorMessage = "Please enter account name.")]
        [StringLength(255, ErrorMessage = "Account name up to 255 characters.")]
        public string AccountName { get; set; }
        [Required(ErrorMessage = "Please choose Bank Payment QR Image.")]
        public string Image { get; set; }
        [Required(ErrorMessage = "Please enter bank branch.")]
        [StringLength(255, ErrorMessage = "Bank branch name up to 255 characters.")]
        public string Branch { get; set; }
        public int Status { get; set; }
    }
}
